# Site settings
title: A blog about Arpit
description: A blog about Arpit
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arpit Jain
user_description: Hi, i'm Arpit and i'm a front end web Developer. i'm currently persuing b.tech in Computer Science Engineering. I'm a Challenger,Lover,Gamer.
user_title: Software Developer
email: maiarpitjain94@gmail.com
twitter_username: arpit0151
github_username:  maiarpitjain94
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
